### ISSUE TITLE
Is this project still maintained?

### ISSUE THREAD

**Issue by luleyleo** [MSzturc/obsidian-better-pdf-plugin#11]
Hello @MSzturc I was wondering whether you are still interested in maintaining this project.

I [fixed the build](https://github.com/luleyleo/obsidian-better-pdf-plugin/commit/10af545b00a47de94ec4d1ab0eb1b094a63ec2ba) and added [support for ranges](https://github.com/luleyleo/obsidian-better-pdf-plugin/commit/4683a978331b9a71c35d0f8583e2170513d515c0) in my fork. Would a PR for that be welcome?

**Comment by MSzturc** [comment]
Yeah sure please create a pull request!

**Comment by luleyleo** [comment]
@MSzturc I opened PRs for the things I implemented in my fork :)

**Comment by MSzturc** [comment]
big thx, i will look at the pull request tomorrow after work

**Comment by MSzturc** [comment]
all of you're fixes have been merged with 1.3.0. Thx for your contribution
