### ISSUE TITLE
Error in the ReadMe

### ISSUE THREAD

**Issue by dummifiedme** [MSzturc/obsidian-better-pdf-plugin#18]
For the `rect` attribute, there is an error in the instructions:
![image](https://user-images.githubusercontent.com/68785729/148726417-e80788de-20cd-4d57-b452-f60fb0514b7d.png)

1. `sizeX, sizeX` repeated.
2. And on trial, I realised `offsetX` is along horizontal, while for `sizeX` it is along the vertical. 

can you confirm what is the exact instruction?
@MSzturc

**Comment by MSzturc** [comment]
thx,fixed
