### ISSUE TITLE
Option to stop hover-over to open pdf-preview

### ISSUE THREAD

**Issue by Gewerd-Strauss** [MSzturc/obsidian-better-pdf-plugin#19]
Hi,

this is an extremely useful plugin, but one thing is kinda detrimental. Obsidian-markdown-files don't necessarily lend themselves to export well because you loose some core functionality such as tag-searches. Hence, most stuff I write in obsidian I also _read_ in it. 

For that, this plugin is a real time-saver over using screen-captures and embedding them as images. However, if I want to embed pages 27-32, I specifically  _don't_ want to open the preview of the entire file whenever I hover over the resulting images in obsidian. Otherwhise, I would just embed the file in its entirety.

As it doesn't seem to be an option right now, would it be possible to include an option to block that behaviour, a simple boolean flag?

Thank you,
Sincerely,
~Gw

**Comment by Hunanbean** [comment]
You are probably aware that 'Core plugins>Page preview' toggle will disable that preview function. of course, everywhere else too.

**Comment by dummifiedme** [comment]
I fixed this part with a snippet to block any hover preview of "PDF" be it this plugin or links. The links could be clicked and opened, but popever is blocked.

**Comment by MSzturc** [comment]
will be fixed with 1.4.0
