### ISSUE TITLE
Poor visual quality on embeded display, regardless of scale setting

### ISSUE THREAD

**Issue by Hunanbean** [MSzturc/obsidian-better-pdf-plugin#20]
i am seeing poor visual quality on embeded display of PDFs, regardless of scale setting.
I have the same PDF diplayed by this plugin, inline, and by the built in Obsidian option. 
The built in option is crystal clear, where this plugins embedded display looks like a 320X240 image zoomed in.
Changing scaling option does change the display, but it never looks 'good'

Thank you

**Comment by dummifiedme** [comment]
+1
Especially when I crop it using rect.

**Comment by laogujimbob** [comment]
Very fuzzy text regardless of scale. I struggle with Chinese characters when they aren't fuzzy!!

**Comment by WizzardMaker** [comment]
I am also experiencing some artifacts
![image](https://user-images.githubusercontent.com/7768485/168799262-6ed0832b-ac37-4786-b738-57a11af3d8dd.png)

**Comment by lisah2u** [comment]
Me, too. Very difficult to read sheet music. But when I set the scale to something much higher (e.g., 4.0), it looks fine.

**Comment by Sinled** [comment]
There is a pr, that fixed this issue,
but no obvious explanation how.

If anyone stumble upon this - for me problem was solved using `fit: true`, and `scale: 2` (correct scale can be found using `window.devicePixelRatio` in obsidian dev tools)
