### ISSUE TITLE
does not work after Obsidian upgraded to v0.13.21

### ISSUE THREAD

**Issue by cshishaliu** [MSzturc/obsidian-better-pdf-plugin#23]
after Obsidian upgraded to (current newest) v0.13.21, the plugin never renders

**Comment by MSzturc** [comment]
Im not Part of the insider Program, so i wont be able to fix this issue until next public release

**Comment by MSzturc** [comment]
I was not able to reproduce this behavior with 0.13.33, please retry with this version
