### ISSUE TITLE
Conflicting versions of PdfJs with Obsidian Insiders Release

### ISSUE THREAD

**Issue by liammagee** [MSzturc/obsidian-better-pdf-plugin#24]
Using the Insiders release, there are conflicting versions of PdfJs, which causes the internal Obsidian loadPdfJs() call to fail. May relate to other issues (e.g. https://github.com/MSzturc/obsidian-better-pdf-plugin/issues/23)

**Comment by MSzturc** [comment]
I was not able to reproduce this behavior with 0.13.33, please retry with this version
