### ISSUE TITLE
PDF page not rendering

### ISSUE THREAD

**Issue by teoryan2** [MSzturc/obsidian-better-pdf-plugin#25]
![image](https://user-images.githubusercontent.com/2877471/154612214-7ca89391-fd16-4fd3-98b4-7b5578627e33.png)
I have written the code correctly but the PDF page isn't rendering in reading view. Anyone can help please! Much appreciated!

**Comment by MSzturc** [comment]
That should actually work, at least I can't see any errors in the syntax. What surprises me is the pagenumber. Does the error also occur with smaller documents?
