### ISSUE TITLE
JavaScript for Adobe Acrobat Pro and AppleScript for Skim for creating automatically the necessary Better PDF Plugin snippet 

### ISSUE THREAD

**Issue by johnsidi** [MSzturc/obsidian-better-pdf-plugin#27]
You can see my scripts here:  https://github.com/johnsidi/scripts-for-Obsidian-Better-PDF-Plugin

**Comment by MSzturc** [comment]
Wow this is awesome, thx for sharing, i will add a link to it in documentation
