### ISSUE TITLE
Add a option to disable showing the PDF viewer when hovering the mouse

### ISSUE THREAD

**Issue by jzhang-brex** [MSzturc/obsidian-better-pdf-plugin#3]
At the moment, I disable that by temporarily commenting out `href.className = "internal-link";`

**Comment by MSzturc** [comment]
this cant be fixed until obsidian changes the behavior of internal links

**Comment by dummifiedme** [comment]
I fixed this part by adding a snippet

```
.popover.hover-popover.pdf-embed{
    display:none;
}
```

It disables the hover preview on both the pages generated by this plugin and on the PDF links. The downside is that even if you press `Ctrl` or `Ctrl+Shift`, popover won't show up.

Works for my use though :)



@jzhang-brex

**Comment by MSzturc** [comment]
Nice find, will be fixed with 1.4.0
