### ISSUE TITLE
Removing preview on hover

### ISSUE THREAD

**Issue by YouvaB** [MSzturc/obsidian-better-pdf-plugin#39]
Hello, 

I love the plugin, very useful and clean. Is there any way to remove the preview on hover? When adding multiple pdf files on the same note, it become very annoying when scrolling down and getting the previews pop up one by one for each file. I've googled around to find any way to stop this with no luck. 

Is there any solution to this? 

Thank you!

**Comment by caticodev** [comment]
@YouvaB You can disable "Link pages by default" in plugin options or add `link: false` in params.

**Comment by YouvaB** [comment]
Oh, I'm sorry I didn't understand that was the purpose of that option, thank you so much!
