### ISSUE TITLE
Option for having a range of pages.

### ISSUE THREAD

**Issue by dummifiedme** [MSzturc/obsidian-better-pdf-plugin#4]
It would be really helpful if there could be a way to include a range of pages instead of listing them with commas. Something like `[21-48]`. If there is an option already present, I couldn't find it mentioned. 

Please help out :)

**Comment by dummifiedme** [comment]
@MSzturc 
Could you please make it a reality?

**Comment by MSzturc** [comment]
Merged pull request! Will be available with 1.3.0
