### ISSUE TITLE
Add option to import whole PDF

### ISSUE THREAD

**Issue by HowToGibbon** [MSzturc/obsidian-better-pdf-plugin#9]
For inserting whole pdf's it would be neat to have the possibility to add a whole pdf.
Maybe make this the default instead of 1  #page.
Since I'm new to contributing on GitHub I pasted the code below, which I would add on Line 37 in main.ts:
```ts
// page parameter as trigger for whole pdf, 0 = all pages
if (parameters.page === 0){
    var pagesArray = [];
    for(var i = 1;i <= pdfjs.getDocument(buffer).numPages; i++){
      pagesArray.push(i);
    }
    parameters.page = pagesArray;
}
```

**Comment by dummifiedme** [comment]
You can fork the repository, make changes and then raise a pull request :)
Else, we would have to wait :D

**Comment by ironfroggy** [comment]
I came here to look for exactly this. Any chance of an update with this addition?
